# Generated by Django 3.0.5 on 2020-05-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='publication_author',
            new_name='pub_author',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='publication_date',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='publication_description',
            new_name='pub_description',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='publication_image',
            new_name='pub_image',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='publication_objective',
            new_name='pub_objective',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='publication_title',
            new_name='pub_title',
        ),
        migrations.AddField(
            model_name='publication',
            name='pub_tags',
            field=models.TextField(default='', verbose_name='Tags'),
            preserve_default=False,
        ),
    ]
